class window.PlayerInfo
    dic: {}	 
	
	get: (key) ->
		@dic[key]

    PlayerInfo::dic['player.female.name'] =  'female'
    PlayerInfo::dic['player.female.sprite.locale'] = 'img'
    PlayerInfo::dic['player.female.sprite.FR'] = '03.png'
    PlayerInfo::dic['player.female.sprite.FL'] = '03.png'
    PlayerInfo::dic['player.female.sprite.BR'] = '11.png'
    PlayerInfo::dic['player.female.sprite.BL'] = '11.png'
	PlayerInfo::dic['player.female.sprite.FL.flip'] = true
	PlayerInfo::dic['player.female.sprite.BL.flip'] = true
    PlayerInfo::dic['player.female.sprite.FL1.flip'] = true
	PlayerInfo::dic['player.female.sprite.FL2.flip'] = true
	PlayerInfo::dic['player.female.sprite.FL3.flip'] = true
	PlayerInfo::dic['player.female.sprite.FL4.flip'] = true
	PlayerInfo::dic['player.female.sprite.FL5.flip'] = true
	PlayerInfo::dic['player.female.sprite.FL6.flip'] = true	
	PlayerInfo::dic['player.female.sprite.BL1.flip'] = true
	PlayerInfo::dic['player.female.sprite.BL2.flip'] = true
	PlayerInfo::dic['player.female.sprite.BL3.flip'] = true
	PlayerInfo::dic['player.female.sprite.BL4.flip'] = true
    PlayerInfo::dic['player.female.sprite.BL5.flip'] = true
    PlayerInfo::dic['player.female.sprite.BL6.flip'] = true
	PlayerInfo::dic['player.female.sprite.FR1'] = '01.png'
    PlayerInfo::dic['player.female.sprite.FR2'] = '02.png'
    PlayerInfo::dic['player.female.sprite.FR3'] = '03.png'
    PlayerInfo::dic['player.female.sprite.FR4'] = '04.png'
    PlayerInfo::dic['player.female.sprite.FR5'] = '05.png'
    PlayerInfo::dic['player.female.sprite.FR6'] = '06.png'	
	PlayerInfo::dic['player.female.sprite.FL1'] = '01.png'
    PlayerInfo::dic['player.female.sprite.FL2'] = '02.png'
    PlayerInfo::dic['player.female.sprite.FL3'] = '03.png'
    PlayerInfo::dic['player.female.sprite.FL4'] = '04.png'
    PlayerInfo::dic['player.female.sprite.FL5'] = '05.png'
    PlayerInfo::dic['player.female.sprite.FL6'] = '06.png'
    PlayerInfo::dic['player.female.sprite.BR1'] = '01.png'
    PlayerInfo::dic['player.female.sprite.BR2'] = '02.png'
    PlayerInfo::dic['player.female.sprite.BR3'] = '03.png'
    PlayerInfo::dic['player.female.sprite.BR4'] = '04.png'
    PlayerInfo::dic['player.female.sprite.BR5'] = '05.png'
    PlayerInfo::dic['player.female.sprite.BR6'] = '06.png'
	PlayerInfo::dic['player.female.sprite.BL1'] = '01.png'
    PlayerInfo::dic['player.female.sprite.BL2'] = '02.png'
    PlayerInfo::dic['player.female.sprite.BL3'] = '03.png'
    PlayerInfo::dic['player.female.sprite.BL4'] = '04.png'
    PlayerInfo::dic['player.female.sprite.BL5'] = '05.png'
    PlayerInfo::dic['player.female.sprite.BL6'] = '06.png'
    PlayerInfo::dic['player.female.sprite.FR.size'] = {w: 58, h: 41}
    PlayerInfo::dic['player.female.sprite.FL.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BR.size'] = {w: 58, h: 41}
    PlayerInfo::dic['player.female.sprite.BL.size'] = {w: 24, h: 43}
    PlayerInfo::dic['player.female.sprite.FR1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FR2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FR3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FR4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FR5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FR6.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.female.sprite.FL1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FL2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FL3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FL4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FL5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.FL6.size'] = {w: 24, h: 52}	
	PlayerInfo::dic['player.female.sprite.BR1.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.female.sprite.BR2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BR3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BR4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BR5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BR6.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.female.sprite.BL1.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.female.sprite.BL2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BL3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BL4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BL5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.female.sprite.BL6.size'] = {w: 24, h: 52}
    
	PlayerInfo::dic['player.male.name'] =  'male'
    PlayerInfo::dic['player.male.sprite.locale'] = 'img'
    PlayerInfo::dic['player.male.sprite.FR'] = '03.png'
    PlayerInfo::dic['player.male.sprite.FL'] = '03.png'
    PlayerInfo::dic['player.male.sprite.BL'] = '11.png'
    PlayerInfo::dic['player.male.sprite.BR'] = '11.png'
	PlayerInfo::dic['player.male.sprite.FL.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL.flip'] = true
    PlayerInfo::dic['player.male.sprite.FL1.flip'] = true
	PlayerInfo::dic['player.male.sprite.FL2.flip'] = true
	PlayerInfo::dic['player.male.sprite.FL3.flip'] = true
	PlayerInfo::dic['player.male.sprite.FL4.flip'] = true
	PlayerInfo::dic['player.male.sprite.FL5.flip'] = true
	PlayerInfo::dic['player.male.sprite.FL6.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL1.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL2.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL3.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL4.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL5.flip'] = true
	PlayerInfo::dic['player.male.sprite.BL6.flip'] = true
	PlayerInfo::dic['player.male.sprite.FR1'] = '01.png'
    PlayerInfo::dic['player.male.sprite.FR2'] = '02.png'
    PlayerInfo::dic['player.male.sprite.FR3'] = '03.png'
    PlayerInfo::dic['player.male.sprite.FR4'] = '04.png'
    PlayerInfo::dic['player.male.sprite.FR5'] = '05.png'
    PlayerInfo::dic['player.male.sprite.FR6'] = '06.png'	
	PlayerInfo::dic['player.male.sprite.FL1'] = '01.png'
    PlayerInfo::dic['player.male.sprite.FL2'] = '02.png'
    PlayerInfo::dic['player.male.sprite.FL3'] = '03.png'
    PlayerInfo::dic['player.male.sprite.FL4'] = '04.png'
    PlayerInfo::dic['player.male.sprite.FL5'] = '05.png'
    PlayerInfo::dic['player.male.sprite.FL6'] = '06.png'
	PlayerInfo::dic['player.male.sprite.BR1'] = '01.png'
    PlayerInfo::dic['player.male.sprite.BR2'] = '02.png'
    PlayerInfo::dic['player.male.sprite.BR3'] = '03.png'
    PlayerInfo::dic['player.male.sprite.BR4'] = '04.png'
    PlayerInfo::dic['player.male.sprite.BR5'] = '05.png'
    PlayerInfo::dic['player.male.sprite.BR6'] = '06.png'	
	PlayerInfo::dic['player.male.sprite.BL1'] = '01.png'
    PlayerInfo::dic['player.male.sprite.BL2'] = '02.png'
    PlayerInfo::dic['player.male.sprite.BL3'] = '03.png'
    PlayerInfo::dic['player.male.sprite.BL4'] = '04.png'
    PlayerInfo::dic['player.male.sprite.BL5'] = '05.png'
    PlayerInfo::dic['player.male.sprite.BL6'] = '06.png'
    PlayerInfo::dic['player.male.sprite.FR.size'] = {w: 58, h: 41}
    PlayerInfo::dic['player.male.sprite.FL.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL.size'] = {w: 58, h: 41}
    PlayerInfo::dic['player.male.sprite.BR.size'] = {w: 24, h: 43}
    PlayerInfo::dic['player.male.sprite.FR1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FR2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FR3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FR4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FR5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FR6.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.male.sprite.FL1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FL2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FL3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FL4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FL5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.FL6.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.male.sprite.BR1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BR2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BR3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BR4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BR5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BR6.size'] = {w: 24, h: 52}
	PlayerInfo::dic['player.male.sprite.BL1.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL2.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL3.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL4.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL5.size'] = {w: 24, h: 52}
    PlayerInfo::dic['player.male.sprite.BL6.size'] = {w: 24, h: 52}
	